"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var vector_1 = require("./vector");
var v1 = new vector_1.Vector(5, 10);
var v2 = new vector_1.Vector(5, 20);
console.log("Vector elements antes de las operaciones:");
v1.print();
v1.add(v2);
console.log("Suma:");
v1.print();
// v1.subs(v2);
// console.log ("Resta:");
// v1.print();
// v1.mult(v2);
// console.log ("Multiplicado");
// v1.print();
// v1.multNumber(v2);
// console.log ("Multiplicado por 2:");
// v1.print();
