"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.movie3 = exports.movie2 = exports.movie1 = void 0;
var movie_1 = require("./movie");
var professional_1 = require("./professional");
var professional1 = new professional_1.Professional("Tilda Swinton", 63, 58, 1.79, false, "British", 1, "Actress");
var professional2 = new professional_1.Professional("Emma Stone", 35, 53, 1.68, false, "American", 1, "Actress");
var professional3 = new professional_1.Professional("Wes Anderson", 54, 72, 1.85, false, "American", 0, "Director");
var professional4 = new professional_1.Professional("Noah Baumbach", 55, 70, 1.78, false, "American", 0, "Writer");
var professional5 = new professional_1.Professional("Greta Gerwig", 40, 60, 1.73, false, "American", 0, "Director");
var professional6 = new professional_1.Professional("Scott Derrickson", 57, 76, 1.82, false, "American", 0, "Director");
var professional7 = new professional_1.Professional("Jon Spaihts", 54, 75, 1.80, false, "American", 0, "Writer");
var movie1 = new movie_1.Movie("The French Dispatch", 2021, "USA", "Comedy/Drama");
exports.movie1 = movie1;
movie1.director = professional3;
movie1.writer = professional4;
movie1.actors.push(professional1, professional2);
movie1.language = "English";
movie1.platform = "Disney+";
movie1.isMCU = false;
movie1.mainCharacterName = "Lucinda Krementz";
movie1.producer = "Wes Anderson";
movie1.distributor = "Searchlight Pictures";
var movie2 = new movie_1.Movie("Barbie", 2023, "USA", "Fantasy/Comedy");
exports.movie2 = movie2;
movie2.director = professional5;
movie2.writer = professional4;
movie2.actors.push(professional2);
movie2.language = "English";
movie2.platform = "HBO Max";
movie2.isMCU = false;
movie2.mainCharacterName = "Barbie";
movie2.producer = "Margot Robbie";
movie2.distributor = "Warner Bros";
var movie3 = new movie_1.Movie("Doctor Strange", 2016, "USA", "Action/Fantasy");
exports.movie3 = movie3;
movie3.director = professional6;
movie3.writer = professional7;
movie3.actors.push(professional1);
movie3.language = "English";
movie3.platform = "Disney+";
movie3.isMCU = true;
movie3.mainCharacterName = "Dr. Stephen Strange";
movie3.producer = "Kevin Feige";
movie3.distributor = "Marvel Studios";
console.log("\n--- The French Dispatch ---");
movie1.printAttributes();
console.log("\n--- Barbie ---");
movie2.printAttributes();
console.log("\n--- Doctor Strange ---");
movie3.printAttributes();
