"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var point_1 = require("./point");
var myPoint = new point_1.Point(3, 7);
console.log("Coordenadas iniciales: ", myPoint.toString());
console.log("Punto X: ", myPoint.getX());
console.log("Punto Y: ", myPoint.getY());
myPoint.setX(10);
myPoint.setY(15);
console.log("Coordenadas actualizadas: ", myPoint.toString());
