"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var point_1 = require("./point");
var myPoint = new point_1.Point(3, 7);
var anotherPoint = new point_1.Point(15, 30);
var point1 = new point_1.Point(1, 2);
var point2 = new point_1.Point(-3, 5);
var point3 = new point_1.Point(7, -4);
console.log("Coordenadas iniciales: ", myPoint.toString());
console.log("Punto X: ", myPoint.getX());
console.log("Punto Y: ", myPoint.getY());
console.log("Distancia al origen: ", myPoint.distanceToOrigin());
myPoint.setX(10);
myPoint.setY(15);
console.log("Coordenadas actualizadas: ", myPoint.toString());
console.log("Nueva distancia al origen: ", myPoint.distanceToOrigin());
console.log("Distancia entre myPoint y anotherPoint: ", myPoint.calculateDistance(anotherPoint));
console.log("Cuadrante de myPoint: ", myPoint.calculateQuadrant());
console.log("Nuevo cuadrante de myPoint: ", myPoint.calculateQuadrant());
var nearestPoint = myPoint.calculateNearest([anotherPoint, point1, point2, point3]);
console.log("El punto más cercano a myPoint es: ", nearestPoint.toString());
